[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "docs/docs"
  command = "cd docs && npx pnpm i --store=node_modules/.pnpm-store && npx pnpm generate"
